apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: bookinfo-gateway-a
  namespace: bookinfo-ingress-a
spec:
  gatewayClassName: istio
  infrastructure:
    labels:
      mesh: tenant-a
    parametersRef:
      group: ""
      kind: ConfigMap
      name: bookinfo-gateway-overrides
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
