apiVersion: v1
kind: ConfigMap
metadata:
  name: waypoint-overrides
  namespace: bookinfo-a
data:
  # The controller specifically looks for the "deployment" key
  deployment: |
    spec:
      template:
        spec:
          nodeSelector:
            mesh: tenant-a
          tolerations:
          - key: "mesh"
            operator: "Equal"
            value: "tenant-a"
            effect: "NoSchedule"
